version: "3"

services:
  master:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator
    ports:
      - "5432"
    volumes:
      - master_data:/bitnami/postgresql

  replica:
    image: bitnami/postgresql:latest
    depends_on:
      - master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - slave_data:/bitnami/postgresql

  pgpool:
    image: bitnami/pgpool:latest
    depends_on:
      - master
    ports:
      - "5432:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:master:5432:4:primary:ALWAYS_PRIMARY,1:replica:5432:6:replica
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_HEALTH_CHECK=1
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
      - PGPOOL_MAX_POOL=1
      - PGPOOL_NUM_INIT_CHILDREN=10
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres

volumes:
  master_data:
    driver: local
  slave_data:
    driver: local
